
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aspire E5-473
 */
public class Tugas2 extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Tugas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelnama = new javax.swing.JLabel();
        jLabelnim = new javax.swing.JLabel();
        jLabeljk = new javax.swing.JLabel();
        jLabelprodi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButtonlk = new javax.swing.JRadioButton();
        jRadioButtonpr = new javax.swing.JRadioButton();
        jTextnama = new javax.swing.JTextField();
        jTextnim = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelagama = new javax.swing.JLabel();
        jComboBoxagama = new javax.swing.JComboBox();
        jLabelalamat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaalamat = new javax.swing.JTextArea();
        jRadioButtonti = new javax.swing.JRadioButton();
        jRadioButtonilkom = new javax.swing.JRadioButton();
        jComboBoxmb = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM PENDAFTARAN MINAT DAN BAKAT");

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabelnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelnama.setText("Nama");

        jLabelnim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelnim.setText("NIM");

        jLabeljk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabeljk.setText("Jenis Kelamin");

        jLabelprodi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelprodi.setText("Prodi");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Minat dan Bakat");

        jRadioButtonlk.setText("Laki-laki");
        jRadioButtonlk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonlkActionPerformed(evt);
            }
        });
        jRadioButtonlk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonlkKeyPressed(evt);
            }
        });

        jRadioButtonpr.setText("Perempuan");

        jTextnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnamaActionPerformed(evt);
            }
        });
        jTextnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextnamaKeyPressed(evt);
            }
        });

        jTextnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextnimActionPerformed(evt);
            }
        });
        jTextnim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextnimKeyPressed(evt);
            }
        });

        jButton1.setText("Simpan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabelagama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelagama.setText("Agama");

        jComboBoxagama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katholik", "Budha", "Hindu", " " }));
        jComboBoxagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxagamaActionPerformed(evt);
            }
        });
        jComboBoxagama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxagamaKeyPressed(evt);
            }
        });

        jLabelalamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabelalamat.setText("Alamat");

        jTextAreaalamat.setColumns(20);
        jTextAreaalamat.setRows(5);
        jTextAreaalamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaalamatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaalamat);

        jRadioButtonti.setText("Teknik Informatika");
        jRadioButtonti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtontiKeyPressed(evt);
            }
        });

        jRadioButtonilkom.setText("Ilmu Komputer");

        jComboBoxmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Analysis", "Desaigner", "Networking", "Programmer" }));
        jComboBoxmb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxmbKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelagama)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelalamat)
                                    .addComponent(jLabeljk)
                                    .addComponent(jLabelprodi))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonlk)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonpr))
                                    .addComponent(jComboBoxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonti)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonilkom)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnama)
                            .addComponent(jLabelnim))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextnama)
                            .addComponent(jTextnim))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnama)
                    .addComponent(jTextnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnim)
                    .addComponent(jTextnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonlk)
                            .addComponent(jRadioButtonpr)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelalamat)
                        .addGap(44, 44, 44)
                        .addComponent(jLabeljk)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelagama)
                    .addComponent(jComboBoxagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelprodi)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonti)
                        .addComponent(jRadioButtonilkom)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        jTextnama.setText("");
        jTextnim.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String Nama = jTextnama.getText();
        String NIM = jTextnim.getText();
        String JK;
            if (jRadioButtonlk.isSelected()){
            JK = jRadioButtonlk.getText();
            }
            else{
                JK = jRadioButtonpr.getText();
            }
        String P;
            if (jRadioButtonti.isSelected()){
            P = jRadioButtonti.getText();
            }
            else{
                P = jRadioButtonilkom.getText();
            }
        JOptionPane.showMessageDialog (this, "Data Tersimpan"+"\n"
        +Nama+"\n"+NIM+"\n"+jTextAreaalamat.getText()+"\n"+JK+"\n"+jComboBoxagama.getSelectedItem()+"\n"+P+"\n"+jComboBoxmb.getSelectedItem());
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonlkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonlkActionPerformed

    private void jTextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnamaActionPerformed

    private void jComboBoxagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxagamaActionPerformed

    private void jTextnamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnamaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jTextnim.requestFocus();
        }
    }//GEN-LAST:event_jTextnamaKeyPressed

    private void jTextnimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextnimKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jTextAreaalamat.requestFocus();
        }
    }//GEN-LAST:event_jTextnimKeyPressed

    private void jTextAreaalamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaalamatKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jRadioButtonlk.requestFocus();
        }
    }//GEN-LAST:event_jTextAreaalamatKeyPressed

    private void jRadioButtonlkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonlkKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jComboBoxagama.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonlkKeyPressed

    private void jComboBoxagamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxagamaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jRadioButtonti.requestFocus();
        }
    }//GEN-LAST:event_jComboBoxagamaKeyPressed

    private void jRadioButtontiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtontiKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jComboBoxmb.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtontiKeyPressed

    private void jComboBoxmbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxmbKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == evt.VK_ENTER)
        {
        jButton1.requestFocus();
        }
    }//GEN-LAST:event_jComboBoxmbKeyPressed

    private void jTextnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextnimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextnimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxagama;
    private javax.swing.JComboBox jComboBoxmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelagama;
    private javax.swing.JLabel jLabelalamat;
    private javax.swing.JLabel jLabeljk;
    private javax.swing.JLabel jLabelnama;
    private javax.swing.JLabel jLabelnim;
    private javax.swing.JLabel jLabelprodi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonilkom;
    private javax.swing.JRadioButton jRadioButtonlk;
    private javax.swing.JRadioButton jRadioButtonpr;
    private javax.swing.JRadioButton jRadioButtonti;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaalamat;
    private javax.swing.JTextField jTextnama;
    private javax.swing.JTextField jTextnim;
    // End of variables declaration//GEN-END:variables
}
